import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // 从 localStorage 读取保存的语言设置
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'zh';
  });

  useEffect(() => {
    // 保存语言设置到 localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'zh' ? 'en' : 'zh');
  };

  const value = {
    language,
    setLanguage,
    toggleLanguage,
    t: (key, params = {}) => {
      // 简单的翻译函数，从 translations 中获取对应的文本
      const template = translations[language]?.[key] || key;

      if (typeof template !== 'string' || !params || Object.keys(params).length === 0) {
        return template;
      }

      return Object.entries(params).reduce(
        (result, [paramKey, paramValue]) => result.split(`{${paramKey}}`).join(String(paramValue ?? '')),
        template
      );
    }
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// 翻译字典
const translations = {
  zh: {
    // Header
    'system.title': '台達設備監控系統',
    'language.switch': '切換語言',
    
    // Tabs
    'tab.dashboard': '設備總覽',
    'tab.groups': '群組設定',
    'tab.alerts': '警報',
    'tab.history': '歷史數據',
    'tab.logs': '系統紀錄',
    'tab.control': '群組控制',
    'tab.industrialControl': '工業控制',
    
    // Sidebar
    'sidebar.dashboard': '設備總覽',
    'sidebar.groups': '群組設定',
    'sidebar.alerts': '警報',
    'sidebar.history': '歷史數據',
    'sidebar.logs': '系統紀錄',
    
    // Dashboard
    'dashboard.title': '設備總覽',
    'dashboard.totalDevices': '總設備數',
    'dashboard.activeDevices': '運作中',
    'dashboard.alerts': '警報',
    'dashboard.efficiency': '效能',
    'dashboard.recentAlerts': '最近警報',
    'dashboard.viewAll': '查看全部',
    'dashboard.device': '設備',
    'dashboard.message': '訊息',
    'dashboard.time': '時間',
    'dashboard.highTemp': '溫度過高',
    'dashboard.pressureAnomaly': '壓力異常',
    'dashboard.connectionLost': '連線中斷',
    'dashboard.ago': '前',
    'dashboard.minutes': '分鐘',
    'dashboard.hours': '小時',
    'dashboard.status': '狀態',
    'dashboard.operational': '運作中',
    'dashboard.warning': '警告',
    'dashboard.error': '錯誤',
    'dashboard.offline': '離線',
    'dashboard.temperature': '溫度',
    'dashboard.pressure': '壓力',
    'dashboard.vibration': '振動',
    'dashboard.details': '詳細資訊',
    'dashboard.maintenance': '維護中',
    'dashboard.groupTitle': '設備群組',
    'dashboard.groupDescription1': '目前顯示',
    'dashboard.groupDescription2': '的設備資訊',
    'dashboard.allGroup':'全部群組',
    'dashboard.allDevicesOption': '全部設備',
    'dashboard.deviceCard.alertBadge': 'ALERT - 高溫警報',
    'dashboard.deviceCard.runningBadge': '運行中',
    'dashboard.deviceCard.waterSection.title': '進/出/回水監測',
    'dashboard.deviceCard.waterSection.in': '入水',
    'dashboard.deviceCard.waterSection.out': '出水',
    'dashboard.deviceCard.waterSection.return': '回水',
    'dashboard.deviceCard.airSection.title': '進風/出風狀態',
    'dashboard.deviceCard.airSection.in': '進風',
    'dashboard.deviceCard.airSection.out': '出風',
    'dashboard.deviceCard.coolingSection.title': '冷排溫度監測',
    'dashboard.deviceCard.coolingSection.leftIn': '左入',
    'dashboard.deviceCard.coolingSection.leftOut': '左出',
    'dashboard.deviceCard.coolingSection.rightIn': '右入',
    'dashboard.deviceCard.coolingSection.rightOut': '右出',
    'dashboard.deviceCard.powerSection.title': '動力系統',
    'dashboard.deviceCard.powerSection.rpm': '轉速',
    'dashboard.deviceCard.powerSection.hz': '頻率',
    'dashboard.noMatchingDevices': '目前沒有符合條件的設備。',
    
    // Group Settings
    'groups.title': '群組設定',
    'groups.createNew': '建立新群組',
    'groups.edit': '編輯',
    'groups.delete': '刪除',
    'groups.operational': '運作中',
    'groups.maintenance': '維護中',
    'groups.devices': '設備',
    'groups.createdAt': '建立時間',
    'groups.confirm.delete': '確定要刪除此群組嗎？',
    'groups.confirm.deleteWithName': '確定要刪除群組「{name}」嗎？',
    'groups.confirm.title': '確認刪除',
    'groups.confirm.cancel': '取消',
    'groups.confirm.confirm': '確認',
    'groups.activeGroups': '啟用中的群組',
    'groups.viewAll': '查看全部',
    'groups.deleteGroup': '刪除群組',
    'groups.deviceManagementTitle': '群組設備管理',
    'groups.defaultGroupName': '群組',
    'groups.deviceManagementDescription': '選擇應在此特定群組中共同監控的設備。您可以選擇以下設備進行分組。',
    'groups.availableDevices': '可用設備',
    'groups.table.select': '選擇',
    'groups.table.deviceId': '設備 ID',
    'groups.table.deviceName': '設備名稱',
    'groups.table.summary': '顯示 {shown} 個設備中的 {total} 個',
    'groups.saveGroupSettings': '儲存群組設定',
    'groups.menu.title': '{name} 操作',
    'groups.menu.prompt': '請選擇 {name} 要執行的操作：',
    'groups.menu.settingsTitle': '群組設定',
    'groups.menu.settingsDescription': '修改群組名稱與包含的設備。調整層級架構與資產分配。',
    'groups.menu.settingsAction': '前往設定',
    'groups.menu.controlTitle': '群組控制',
    'groups.menu.controlDescription': '統一控制風扇轉速、量測頻率與開關。執行即時批次指令操作。',
    'groups.menu.controlAction': '開啟面板',
    'groups.error.fetchGroups': '群組獲取失敗:',
    'groups.error.fetchDevices': '設備獲取失敗:',
    'groups.error.deleteMissingId': '找不到可刪除的群組 ID',
    'groups.error.deleteFailed': '刪除群組失敗',
    'groups.error.saveMissingId': '找不到群組 ID，無法保存設備設定',
    'groups.error.saveDevicesFailed': '保存群組設備失敗',
    'groups.error.saveGroupFailed': '保存失敗，請確認群組名稱是否符合後端規格',
    'groups.log.deviceAdded': '群組設備新增',
    'groups.log.deviceRemoved': '群組設備移除',
    'groups.log.deleteFailed': '群組刪除失敗:',
    'groups.log.saveDevicesFailed': '群組設備保存失敗:',
    'groups.log.saveGroupFailed': '群組保存失敗:',
    
    // Alarm
    'alarm.title': '警報管理',
    'alarm.filter.all': '全部',
    'alarm.filter.critical': '嚴重',
    'alarm.filter.warning': '警告',
    'alarm.filter.info': '資訊',
    'alarm.severity': '嚴重性',
    'alarm.device': '設備',
    'alarm.message': '訊息',
    'alarm.timestamp': '時間戳記',
    'alarm.status': '狀態',
    'alarm.actions': '操作',
    'alarm.active': '進行中',
    'alarm.acknowledged': '已確認',
    'alarm.resolved': '已解決',
    'alarm.acknowledge': '確認',
    'alarm.resolve': '解決',
    'alarm.recordList': '警報紀錄',

    'alarm.deviceName': '設備名稱',
    'alarm.deviceIp': '設備 IP',
    'alarm.description': '異常說明',
    'alarm.loading': '警報資料載入中...',
    'alarm.empty': '目前沒有警報資料。',
    'alarm.fetchError': '載入警報資料失敗: {message}',
    'alarm.paginationSummary': '顯示第 {start} 到 {end} 筆，共 {total} 筆結果',
    'alarm.pageSummary': '每頁 {size} 筆，共 {total} 筆',
    
    // History
    'history.title': '歷史數據',
    'history.device': '設備',
    'history.selectDevice': '選擇設備',
    'history.dateRange': '日期範圍',
    'history.from': '開始日期',
    'history.to': '結束日期',
    'history.query': '查詢',
    'history.export': '匯出',
    'history.timestamp': '時間戳記',
    'history.noData': '沒有數據',
    'history.loading': '載入中...',
    'history.error': '載入失敗',
    
    // HistoryList specific
    'filter_conditions': '篩選條件',
    'select_device': '選擇設備',
    'please_select_device': '請選擇設備',
    'start_datetime': '開始日期時間',
    'end_datetime': '結束日期時間',
    'optional': '選填',
    'default': '預設',
    'querying': '查詢中',
    'query_data': '查詢數據',
    'device': '設備',
    'time_range': '時間範圍',
    'total': '總共',
    'records': '筆',
    'time': '時間',
    'device_id': '設備編號',
    'sensor': '感測器',
    'value': '數值',
    'loading_data': '載入數據中...',
    'no_data': '查無資料',
    'history.no_data_found': '查無資料',
    'history.no_matching_data': '查無符合資料',
    'please_set_filter': '請設定篩選條件並查詢',
    'showing': '顯示',
    'to': '至',
    'of': '共',
    'entries': '筆資料',
    'items_per_page': '每頁筆數',
    'items': '筆',
    'jump_to_page': '跳至頁數',
    'go': '前往',
    
    // Industrial Control
    'industrial.title': '工業控制',
    'industrial.deviceSelect': '設備選擇',
    'industrial.selectDevice': '選擇設備',
    'industrial.controls': '控制',
    'industrial.monitoring': '監控',
    'industrial.settings': '設定',
    'industrial.start': '啟動',
    'industrial.stop': '停止',
    'industrial.reset': '重置',
    'industrial.emergency': '緊急停止',
    'industrial.speed': '速度',
    'industrial.temperature': '溫度',
    'industrial.pressure': '壓力',
    'industrial.status': '狀態',
    'industrial.running': '運行中',
    'industrial.stopped': '已停止',
    'industrial.error': '錯誤',
    'industrial.deviceTitle': '設備 {id}',
    'industrial.deviceSerial': '編號：DEV-{id}',
    'industrial.status.normal': '系統正常',
    'industrial.status.alert': '異常警示',
    'industrial.status.warning': '需要注意',
    'industrial.status.offline': '設備離線',
    'industrial.telemetry.inletWaterData': '入水數據',
    'industrial.telemetry.outletWaterData': '出水數據',
    'industrial.telemetry.returnWaterData': '回水數據',
    'industrial.telemetry.coilWaterMonitoring': '盤管水溫監控',
    'industrial.telemetry.inletAirTempHumidity': '入風溫濕度',
    'industrial.telemetry.outletAirTemperature': '出風溫度',
    'industrial.metric.humidity': '濕度',
    'industrial.metric.leftIn': '左 入',
    'industrial.metric.leftOut': '左 出',
    'industrial.metric.rightIn': '右 入',
    'industrial.metric.rightOut': '右 出',
    'industrial.outletValveControl': '出水閥控制',
    'industrial.mixingValveControl': '混水閥控制',
    'industrial.mixingPumpControl': '混水泵浦控制',
    'industrial.pidEnabled': 'PID 已啟用',
    'industrial.pidStartMonitoring': 'PID 啟動監控',
    'industrial.forwardCorrection': '正向修正',
    'industrial.openingRatio': '開度比例',
    'industrial.setValue': '設定數值',
    'industrial.targetFrequency': '目標頻率',
    'industrial.targetTemperature': '目標溫度',
    'industrial.currentFlowRate': '當前水流量',
    'industrial.currentHeatExchange': '當前熱交換',
    'industrial.flowUnit': 'L/min',
    'industrial.fanControl': '風扇控制',
    'industrial.oneClickEnableAll': '一鍵開啟全部',
    'industrial.differentialPressureControl': '壓差控制',
    'industrial.pidSettings': 'PID 設定',
    'industrial.targetSpeed': '目標轉速',
    'industrial.rpmUnit': 'RPM',
    'industrial.fanLabel': '風扇',
    'industrial.error.fetchSensor': '設備感測資料獲取失敗:',
    
    // Group Control
    'groupControl.title': '群組控制',
    'groupControl.back': '返回',
    'groupControl.devices': '設備',
    'groupControl.selectAll': '全選',
    'groupControl.deselectAll': '取消全選',
    'groupControl.startSelected': '啟動選取的設備',
    'groupControl.stopSelected': '停止選取的設備',
    'groupControl.status': '狀態',
    'groupControl.actions': '操作',
    'groupControl.start': '啟動',
    'groupControl.stop': '停止',
    'groupControl.saved': '儲存成功',
    'groupControl.manageGroup': '管理 {name} 內的所有機台',
    'groupControl.systemStatus': '系統狀態',
    'groupControl.running': '運行中',
    'groupControl.masterPowerTitle': '主電源系統',
    'groupControl.masterPowerDescription': '同步切換所有風扇',
    'groupControl.samplingFrequency': '取樣頻率',
    'groupControl.samplingFrequencyDescription': '感測器更新間隔',
    'groupControl.milliseconds': 'ms',
    'groupControl.individualFanControl': '單機風扇控制',
    'groupControl.fanName': '風扇',
    'groupControl.fault': '故障',
    'groupControl.operating': '運轉中',
    'groupControl.standby': '待命',
    'groupControl.setFanSpeed': '設定風扇轉速',
    'groupControl.rpmUnit': 'RPM',
    'groupControl.manualResetRequired': '需要手動重置',
    'groupControl.discardChanges': '捨棄變更',
    'groupControl.applyChanges': '套用變更',
    
    // Configuration Panel
    'config.title': '配置面板',
    'config.device': '設備',
    'config.group': '群組',
    'config.sensors': '感測器',
    'config.thresholds': '閾值',
    'config.notifications': '通知',
    'config.save': '儲存',
    'config.cancel': '取消',
    'config.apply': '套用',
    'config.saved': '儲存成功',
    'config.subtitle': '建立新群組並選擇包含的設備',
    'config.groupNameLabel': '群組名稱',
    'config.groupNamePlaceholder': '例如：Group A',
    'config.apiHint': '目前建立群組 API 只需要群組名稱。設備綁定若需要，應由其他 API 或後續編輯流程處理。',
    'config.error.groupNameRequired': '請輸入群組名稱',
    
    // Common
    'common.save': '儲存',
    'common.cancel': '取消',
    'common.delete': '刪除',
    'common.edit': '編輯',
    'common.add': '新增',
    'common.remove': '移除',
    'common.confirm': '確認',
    'common.close': '關閉',
    'common.loading': '載入中...',
    'common.error': '錯誤',
    'common.success': '成功',
    'common.warning': '警告',
    'common.info': '資訊',
    'common.search': '搜尋',
    'common.filter': '篩選',
    'common.export': '匯出',
    'common.import': '匯入',
    'common.refresh': '重新整理',
    'common.settings': '設定',
    'common.saveSuccess': '儲存成功',
    'common.saving': '儲存中...',
    'common.deleting': '刪除中...',
    'common.saveChanges': '儲存變更',
    'common.applyChanges': '套用變更',
    'common.discardChanges': '捨棄變更',
  },
  en: {
    // Header
    'system.title': 'Delta Device Monitoring System',
    'language.switch': 'Switch Language',
    
    // Tabs
    'tab.dashboard': 'Dashboard',
    'tab.groups': 'Group Settings',
    'tab.alerts': 'Alerts',
    'tab.history': 'History',
    'tab.logs': 'System Logs',
    'tab.control': 'Group Control',
    'tab.industrialControl': 'Industrial Control',
    
    // Sidebar
    'sidebar.dashboard': 'Dashboard',
    'sidebar.groups': 'Group Settings',
    'sidebar.alerts': 'Alerts',
    'sidebar.history': 'History',
    'sidebar.logs': 'System Logs',
    
    // Dashboard
    'dashboard.title': 'Device Dashboard',
    'dashboard.totalDevices': 'Total Devices',
    'dashboard.activeDevices': 'Active',
    'dashboard.alerts': 'Alerts',
    'dashboard.efficiency': 'Efficiency',
    'dashboard.recentAlerts': 'Recent Alerts',
    'dashboard.viewAll': 'View All',
    'dashboard.device': 'Device',
    'dashboard.message': 'Message',
    'dashboard.time': 'Time',
    'dashboard.highTemp': 'High Temperature',
    'dashboard.pressureAnomaly': 'Pressure Anomaly',
    'dashboard.connectionLost': 'Connection Lost',
    'dashboard.ago': 'ago',
    'dashboard.minutes': 'minutes',
    'dashboard.hours': 'hours',
    'dashboard.status': 'Status',
    'dashboard.operational': 'Operational',
    'dashboard.warning': 'Warning',
    'dashboard.error': 'Error',
    'dashboard.offline': 'Offline',
    'dashboard.temperature': 'Temperature',
    'dashboard.pressure': 'Pressure',
    'dashboard.vibration': 'Vibration',
    'dashboard.details': 'Details',
    'dashboard.maintenance': 'Maintenance',
    'dashboard.groupTitle': 'Device Group',
    'dashboard.groupDescription1': 'Currently showing',
    'dashboard.groupDescription2': 'device information',
    'dashboard.allGroup': 'All Groups',
    'dashboard.allDevicesOption': 'All Devices',
    'dashboard.deviceCard.alertBadge': 'ALERT - High Temperature',
    'dashboard.deviceCard.runningBadge': 'Running',
    'dashboard.deviceCard.waterSection.title': 'Inlet/Outlet/Return Water Monitoring',
    'dashboard.deviceCard.waterSection.in': 'Inlet Water',
    'dashboard.deviceCard.waterSection.out': 'Outlet Water',
    'dashboard.deviceCard.waterSection.return': 'Return Water',
    'dashboard.deviceCard.airSection.title': 'Inlet/Outlet Air Status',
    'dashboard.deviceCard.airSection.in': 'Inlet Air',
    'dashboard.deviceCard.airSection.out': 'Outlet Air',
    'dashboard.deviceCard.coolingSection.title': 'Cooling Coil Temperature Monitoring',
    'dashboard.deviceCard.coolingSection.leftIn': 'Left In',
    'dashboard.deviceCard.coolingSection.leftOut': 'Left Out',
    'dashboard.deviceCard.coolingSection.rightIn': 'Right In',
    'dashboard.deviceCard.coolingSection.rightOut': 'Right Out',
    'dashboard.deviceCard.powerSection.title': 'Power System',
    'dashboard.deviceCard.powerSection.rpm': 'Speed',
    'dashboard.deviceCard.powerSection.hz': 'Frequency',
    'dashboard.noMatchingDevices': 'No devices match the current filters.',
    
    // Group Settings
    'groups.title': 'Group Settings',
    'groups.createNew': 'Create New Group',
    'groups.edit': 'Edit',
    'groups.delete': 'Delete',
    'groups.operational': 'Operational',
    'groups.maintenance': 'Maintenance',
    'groups.devices': 'Devices',
    'groups.createdAt': 'Created',
    'groups.confirm.delete': 'Are you sure you want to delete this group?',
    'groups.confirm.deleteWithName': 'Are you sure you want to delete group "{name}"?',
    'groups.confirm.title': 'Confirm Delete',
    'groups.confirm.cancel': 'Cancel',
    'groups.confirm.confirm': 'Confirm',
    'groups.activeGroups': 'Active Groups',
    'groups.viewAll': 'View All',
    'groups.deleteGroup': 'Delete Group',
    'groups.deviceManagementTitle': 'Group Device Management',
    'groups.defaultGroupName': 'Group',
    'groups.deviceManagementDescription': 'Select devices that should be monitored together in this specific group. You can choose from the available devices below to form your group.',
    'groups.availableDevices': 'Available Devices',
    'groups.table.select': 'Select',
    'groups.table.deviceId': 'Device ID',
    'groups.table.deviceName': 'Device Name',
    'groups.table.summary': 'Showing {shown} of {total} devices',
    'groups.saveGroupSettings': 'Save Group Settings',
    'groups.menu.title': '{name} Actions',
    'groups.menu.prompt': 'Choose an action for {name}:',
    'groups.menu.settingsTitle': 'Group Settings',
    'groups.menu.settingsDescription': 'Update the group name and included devices. Adjust hierarchy and asset allocation.',
    'groups.menu.settingsAction': 'Open Settings',
    'groups.menu.controlTitle': 'Group Control',
    'groups.menu.controlDescription': 'Control fan speed, sampling frequency, and power states in batch with real-time commands.',
    'groups.menu.controlAction': 'Open Panel',
    'groups.error.fetchGroups': 'Failed to fetch groups:',
    'groups.error.fetchDevices': 'Failed to fetch devices:',
    'groups.error.deleteMissingId': 'Cannot find a group ID to delete',
    'groups.error.deleteFailed': 'Failed to delete the group.',
    'groups.error.saveMissingId': 'Cannot find a group ID, so device settings cannot be saved',
    'groups.error.saveDevicesFailed': 'Failed to save group devices.',
    'groups.error.saveGroupFailed': 'Save failed. Please confirm the group name matches backend requirements',
    'groups.log.deviceAdded': 'Group device added',
    'groups.log.deviceRemoved': 'Group device removed',
    'groups.log.deleteFailed': 'Failed to delete group:',
    'groups.log.saveDevicesFailed': 'Failed to save group devices:',
    'groups.log.saveGroupFailed': 'Failed to save group:',
    
    // Alarm
    'alarm.title': 'Alarm Management',
    'alarm.filter.all': 'All',
    'alarm.filter.critical': 'Critical',
    'alarm.filter.warning': 'Warning',
    'alarm.filter.info': 'Info',
    'alarm.severity': 'Severity',
    'alarm.device': 'Device',
    'alarm.message': 'Message',
    'alarm.timestamp': 'Timestamp',
    'alarm.status': 'Status',
    'alarm.actions': 'Actions',
    'alarm.active': 'Active',
    'alarm.acknowledged': 'Acknowledged',
    'alarm.resolved': 'Resolved',
    'alarm.acknowledge': 'Acknowledge',
    'alarm.resolve': 'Resolve',
    'alarm.recordList': 'Alarm Records',

    'alarm.deviceName': 'Device Name',
    'alarm.deviceIp': 'Device IP',
    'alarm.description': 'Description',
    'alarm.loading': 'Loading alarm data...',
    'alarm.empty': 'There is currently no alarm data.',
    'alarm.fetchError': 'Failed to load alarm data: {message}',
    'alarm.paginationSummary': 'Showing {start} to {end} of {total} results',
    'alarm.pageSummary': '{size} per page, {total} total',
    
    // History
    'history.title': 'History Data',
    'history.device': 'Device',
    'history.selectDevice': 'Select Device',
    'history.dateRange': 'Date Range',
    'history.from': 'From',
    'history.to': 'To',
    'history.query': 'Query',
    'history.export': 'Export',
    'history.timestamp': 'Timestamp',
    'history.noData': 'No Data',
    'history.loading': 'Loading...',
    'history.error': 'Failed to Load',
    
    // HistoryList specific
    'filter_conditions': 'Filter Conditions',
    'select_device': 'Select Device',
    'please_select_device': 'Please select a device',
    'start_datetime': 'Start DateTime',
    'end_datetime': 'End DateTime',
    'optional': 'Optional',
    'default': 'Default',
    'querying': 'Querying',
    'query_data': 'Query Data',
    'device': 'Device',
    'time_range': 'Time Range',
    'total': 'Total',
    'records': 'Records',
    'time': 'Time',
    'device_id': 'Device ID',
    'sensor': 'Sensor',
    'value': 'Value',
    'loading_data': 'Loading data...',
    'no_data': 'No data',
    'history.no_data_found': 'No data found',
    'history.no_matching_data': 'No matching data found',
    'please_set_filter': 'Please set filter conditions and query',
    'showing': 'Showing',
    'to': 'to',
    'of': 'of',
    'entries': 'entries',
    'items_per_page': 'Items per page',
    'items': 'items',
    'jump_to_page': 'Jump to page',
    'go': 'Go',
    
    // Industrial Control
    'industrial.title': 'Industrial Control',
    'industrial.deviceSelect': 'Device Selection',
    'industrial.selectDevice': 'Select Device',
    'industrial.controls': 'Controls',
    'industrial.monitoring': 'Monitoring',
    'industrial.settings': 'Settings',
    'industrial.start': 'Start',
    'industrial.stop': 'Stop',
    'industrial.reset': 'Reset',
    'industrial.emergency': 'Emergency Stop',
    'industrial.speed': 'Speed',
    'industrial.temperature': 'Temperature',
    'industrial.pressure': 'Pressure',
    'industrial.status': 'Status',
    'industrial.running': 'Running',
    'industrial.stopped': 'Stopped',
    'industrial.error': 'Error',
    'industrial.deviceTitle': 'Device {id}',
    'industrial.deviceSerial': 'ID: DEV-{id}',
    'industrial.status.normal': 'System Normal',
    'industrial.status.alert': 'Alert',
    'industrial.status.warning': 'Needs Attention',
    'industrial.status.offline': 'Device Offline',
    'industrial.telemetry.inletWaterData': 'Inlet Water Data',
    'industrial.telemetry.outletWaterData': 'Outlet Water Data',
    'industrial.telemetry.returnWaterData': 'Return Water Data',
    'industrial.telemetry.coilWaterMonitoring': 'Coil Water Temperature Monitoring',
    'industrial.telemetry.inletAirTempHumidity': 'Inlet Air Temperature & Humidity',
    'industrial.telemetry.outletAirTemperature': 'Outlet Air Temperature',
    'industrial.metric.humidity': 'Humidity',
    'industrial.metric.leftIn': 'Left In',
    'industrial.metric.leftOut': 'Left Out',
    'industrial.metric.rightIn': 'Right In',
    'industrial.metric.rightOut': 'Right Out',
    'industrial.outletValveControl': 'Outlet Valve Control',
    'industrial.mixingValveControl': 'Mixing Valve Control',
    'industrial.mixingPumpControl': 'Mixing Pump Control',
    'industrial.pidEnabled': 'PID Enabled',
    'industrial.pidStartMonitoring': 'PID Start Monitoring',
    'industrial.forwardCorrection': 'Forward Correction',
    'industrial.openingRatio': 'Opening Ratio',
    'industrial.setValue': 'Set Value',
    'industrial.targetFrequency': 'Target Frequency',
    'industrial.targetTemperature': 'Target Temperature',
    'industrial.currentFlowRate': 'Current Flow Rate',
    'industrial.currentHeatExchange': 'Current Heat Exchange',
    'industrial.flowUnit': 'L/min',
    'industrial.fanControl': 'Fan Control',
    'industrial.oneClickEnableAll': 'Enable All with One Click',
    'industrial.differentialPressureControl': 'Differential Pressure Control',
    'industrial.pidSettings': 'PID Settings',
    'industrial.targetSpeed': 'Target Speed',
    'industrial.rpmUnit': 'RPM',
    'industrial.fanLabel': 'Fan',
    'industrial.error.fetchSensor': 'Failed to fetch device sensor data:',
    
    // Group Control
    'groupControl.title': 'Group Control',
    'groupControl.back': 'Back',
    'groupControl.devices': 'Devices',
    'groupControl.selectAll': 'Select All',
    'groupControl.deselectAll': 'Deselect All',
    'groupControl.startSelected': 'Start Selected',
    'groupControl.stopSelected': 'Stop Selected',
    'groupControl.status': 'Status',
    'groupControl.actions': 'Actions',
    'groupControl.start': 'Start',
    'groupControl.stop': 'Stop',
    'groupControl.saved': 'Saved successfully',
    'groupControl.manageGroup': 'Manage all units in {name}',
    'groupControl.systemStatus': 'System Status',
    'groupControl.running': 'Running',
    'groupControl.masterPowerTitle': 'Main Power System',
    'groupControl.masterPowerDescription': 'Toggle all fans together',
    'groupControl.samplingFrequency': 'Sampling Frequency',
    'groupControl.samplingFrequencyDescription': 'Sensor update interval',
    'groupControl.milliseconds': 'ms',
    'groupControl.individualFanControl': 'Individual Fan Control',
    'groupControl.fanName': 'Fan #{id}',
    'groupControl.fault': 'Fault',
    'groupControl.operating': 'Running',
    'groupControl.standby': 'Standby',
    'groupControl.setFanSpeed': 'Set Fan Speed',
    'groupControl.rpmUnit': 'RPM',
    'groupControl.manualResetRequired': 'Manual reset required',
    'groupControl.discardChanges': 'Discard Changes',
    'groupControl.applyChanges': 'Apply Changes',
    
    // Configuration Panel
    'config.title': 'Configuration Panel',
    'config.device': 'Device',
    'config.group': 'Group',
    'config.sensors': 'Sensors',
    'config.thresholds': 'Thresholds',
    'config.notifications': 'Notifications',
    'config.save': 'Save',
    'config.cancel': 'Cancel',
    'config.apply': 'Apply',
    'config.saved': 'Saved successfully',
    'config.subtitle': 'Create a new group and choose the devices it contains',
    'config.groupNameLabel': 'Group Name',
    'config.groupNamePlaceholder': 'Example: First Floor Cooling System',
    'config.apiHint': 'The current create-group API only requires a group name. If device binding is needed, it should be handled by another API or a later editing flow.',
    'config.error.groupNameRequired': 'Please enter a group name',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.settings': 'Settings',
    'common.saveSuccess': 'Saved successfully',
    'common.saving': 'Saving...',
    'common.deleting': 'Deleting...',
    'common.saveChanges': 'Save Changes',
    'common.applyChanges': 'Apply Changes',
    'common.discardChanges': 'Discard Changes',
  }
};

